apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-control-plane
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: { app: {{ .Release.Name }}-control-plane }
  template:
    metadata:
      labels: { app: {{ .Release.Name }}-control-plane }
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports: [{ containerPort: 8000 }]
